projects:
  tiledb:
    type: feedstock
    ref: dev
    url: "https://github.com/conda-forge/tiledb-feedstock"
  tiledb-py:
    depends: tiledb
    type: feedstock
    ref: dev
    url: "https://github.com/conda-forge/tiledb-py-feedstock"
    extra_meta:
      python_impl: cpython
  tiledb-vcf:
    depends: tiledb-py
    type: feedstock
    ref: master
    url: "https://github.com/TileDB-Inc/tiledb-vcf-feedstock.git"
  tiledb-soma:
    depends: tiledb-py
    type: feedstock
    ref: master
    url: "https://github.com/TileDB-Inc/tiledbsoma-feedstock.git"
  tiledb-vector-search:
    depends: tiledb-py
    type: feedstock
    ref: main
    url: "https://github.com/TileDB-Inc/tiledb-vector-search-feedstock.git"
