projects:
  tiledb:
    type: feedstock
    ref: dev
    url: "https://github.com/conda-forge/tiledb-feedstock"
    config: "linux_64_gcsgcs_enabledlibcurl8openssl3"
  tiledb-py:
    type: feedstock
    ref: dev
    url: "https://github.com/conda-forge/tiledb-py-feedstock"
    config: "linux_64_numpy1.22python3.8.____cpython"
